declare module "@formfusion/iban" {
  type IbanPatterns = {
    AD: string;
    AE: string;
    AL: string;
    AT: string;
    AZ: string;
    BA: string;
    BE: string;
    BG: string;
    BH: string;
    BR: string;
    BY: string;
    CH: string;
    CR: string;
    CY: string;
    CZ: string;
    DE: string;
    DK: string;
    DO: string;
    EE: string;
    EG: string;
    ES: string;
    FI: string;
    FO: string;
    FR: string;
    GB: string;
    GE: string;
    GI: string;
    GL: string;
    GR: string;
    GT: string;
    HR: string;
    HU: string;
    IE: string;
    IL: string;
    IQ: string;
    IR: string;
    IS: string;
    IT: string;
    JO: string;
    KW: string;
    KZ: string;
    LB: string;
    LC: string;
    LI: string;
    LT: string;
    LU: string;
    LV: string;
    MA: string;
    MC: string;
    MD: string;
    ME: string;
    MK: string;
    MR: string;
    MT: string;
    MU: string;
    MZ: string;
    NL: string;
    NO: string;
    PK: string;
    PL: string;
    PS: string;
    PT: string;
    QA: string;
    RO: string;
    RS: string;
    SA: string;
    SC: string;
    SE: string;
    SI: string;
    SK: string;
    SM: string;
    SV: string;
    TL: string;
    TN: string;
    TR: string;
    UA: string;
    VA: string;
    VG: string;
    XK: string;
  };

  type LowercaseKeys<T> = {
    [K in keyof T as K extends string ? Lowercase<K> : never]: T[K];
  };

  const iban: LowercaseKeys<IbanPatterns>;

  export = iban;
}
